name: Install requirements
description: Install a version of python then call pip install and report what was installed
inputs:
  python-version:
    description: Python version to install
    default: "3.12"
  pip-install:
    description: Parameters to pass to pip install
    default: "-e .[dev]"

runs:
  using: composite
  steps:
    - name: Get version of python
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}"
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install packages
      run: pip install ${{ inputs.pip-install }}
      shell: bash

    - name: Install custom MineDojo
      run: |
        git clone --depth=1 --single-branch https://github.com/thomashopkins32/MineDojo.git
        pip install ./MineDojo

    - name: Report what was installed
      run: pip freeze
      shell: bash
