# Configuration template for running the engine
# See dataclass definitions for the full specification

# Engine settings
engine:
  image_size: !!python/tuple [160, 256]
  max_steps: 10000

# Agent settings
agent:
  ppo:
    clip_ratio: 0.2 # Gradient clipping ratio
    target_kl: 0.01 # Target KL-divergence for model selection
    actor_lr: 3.0e-4 # Actor learning rate
    critic_lr: 1.0e-3 # Critic learning rate
    train_actor_iters: 80 # Number of iterations to train actor
    train_critic_iters: 80 # Number of iterations to train critic
  max_buffer_size: 50
  roi_shape: !!python/tuple [32, 32]
  discount_factor: 0.99
  gae_discount_factor: 0.97