name: Java Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.44.0
          cache: false
          frozen: true
          locked: false
          environments: ["default"]

      - name: Build with Gradle
        run: |
          cd forge
          pixi run minecraft-build
