name: Pre-commit

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          args: --all-files
