name: Run pytest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install python packages
      uses: ./.github/actions/install_requirements
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pytest
      run: pytest ./tests